before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/api
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
archives:
- id: vke-application-archive
  name_template: |-
    vke-application_{{.Tag}}_{{.Os}}_{{.Arch}}
  builds:
    - vke-application
  files:
    - locale
    - scripts/rke2-init-sh.tpl
    - README.md