// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmindtech/vke/internal/repository (interfaces: IRepository,IClusterRepository,IJobsRepository,IAuditLogRepository,IKubeconfigRepository,INodeGroupsRepository,IResourcesRepository,IErrorRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/repository_mock.go -package=mocks github.com/vmindtech/vke/internal/repository IRepository,IClusterRepository,IJobsRepository,IAuditLogRepository,IKubeconfigRepository,INodeGroupsRepository,IResourcesRepository,IErrorRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/vmindtech/vke/internal/model"
	repository "github.com/vmindtech/vke/internal/repository"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
	isgomock struct{}
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// AuditLog mocks base method.
func (m *MockIRepository) AuditLog() repository.IAuditLogRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuditLog")
	ret0, _ := ret[0].(repository.IAuditLogRepository)
	return ret0
}

// AuditLog indicates an expected call of AuditLog.
func (mr *MockIRepositoryMockRecorder) AuditLog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuditLog", reflect.TypeOf((*MockIRepository)(nil).AuditLog))
}

// Cluster mocks base method.
func (m *MockIRepository) Cluster() repository.IClusterRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cluster")
	ret0, _ := ret[0].(repository.IClusterRepository)
	return ret0
}

// Cluster indicates an expected call of Cluster.
func (mr *MockIRepositoryMockRecorder) Cluster() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cluster", reflect.TypeOf((*MockIRepository)(nil).Cluster))
}

// CommitDBTransaction mocks base method.
func (m *MockIRepository) CommitDBTransaction(tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitDBTransaction", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitDBTransaction indicates an expected call of CommitDBTransaction.
func (mr *MockIRepositoryMockRecorder) CommitDBTransaction(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitDBTransaction", reflect.TypeOf((*MockIRepository)(nil).CommitDBTransaction), tx)
}

// Error mocks base method.
func (m *MockIRepository) Error() repository.IErrorRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(repository.IErrorRepository)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockIRepositoryMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockIRepository)(nil).Error))
}

// Jobs mocks base method.
func (m *MockIRepository) Jobs() repository.IJobsRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Jobs")
	ret0, _ := ret[0].(repository.IJobsRepository)
	return ret0
}

// Jobs indicates an expected call of Jobs.
func (mr *MockIRepositoryMockRecorder) Jobs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Jobs", reflect.TypeOf((*MockIRepository)(nil).Jobs))
}

// Kubeconfig mocks base method.
func (m *MockIRepository) Kubeconfig() repository.IKubeconfigRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kubeconfig")
	ret0, _ := ret[0].(repository.IKubeconfigRepository)
	return ret0
}

// Kubeconfig indicates an expected call of Kubeconfig.
func (mr *MockIRepositoryMockRecorder) Kubeconfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kubeconfig", reflect.TypeOf((*MockIRepository)(nil).Kubeconfig))
}

// NodeGroups mocks base method.
func (m *MockIRepository) NodeGroups() repository.INodeGroupsRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NodeGroups")
	ret0, _ := ret[0].(repository.INodeGroupsRepository)
	return ret0
}

// NodeGroups indicates an expected call of NodeGroups.
func (mr *MockIRepositoryMockRecorder) NodeGroups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeGroups", reflect.TypeOf((*MockIRepository)(nil).NodeGroups))
}

// Resources mocks base method.
func (m *MockIRepository) Resources() repository.IResourcesRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resources")
	ret0, _ := ret[0].(repository.IResourcesRepository)
	return ret0
}

// Resources indicates an expected call of Resources.
func (mr *MockIRepositoryMockRecorder) Resources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resources", reflect.TypeOf((*MockIRepository)(nil).Resources))
}

// StartDBTransaction mocks base method.
func (m *MockIRepository) StartDBTransaction(ctx context.Context) (*gorm.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDBTransaction", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDBTransaction indicates an expected call of StartDBTransaction.
func (mr *MockIRepositoryMockRecorder) StartDBTransaction(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDBTransaction", reflect.TypeOf((*MockIRepository)(nil).StartDBTransaction), ctx)
}

// MockIClusterRepository is a mock of IClusterRepository interface.
type MockIClusterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIClusterRepositoryMockRecorder
	isgomock struct{}
}

// MockIClusterRepositoryMockRecorder is the mock recorder for MockIClusterRepository.
type MockIClusterRepositoryMockRecorder struct {
	mock *MockIClusterRepository
}

// NewMockIClusterRepository creates a new mock instance.
func NewMockIClusterRepository(ctrl *gomock.Controller) *MockIClusterRepository {
	mock := &MockIClusterRepository{ctrl: ctrl}
	mock.recorder = &MockIClusterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClusterRepository) EXPECT() *MockIClusterRepositoryMockRecorder {
	return m.recorder
}

// ClearLoadbalancerUUIDIfMatches mocks base method.
func (m *MockIClusterRepository) ClearLoadbalancerUUIDIfMatches(ctx context.Context, clusterUUID, loadBalancerUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearLoadbalancerUUIDIfMatches", ctx, clusterUUID, loadBalancerUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearLoadbalancerUUIDIfMatches indicates an expected call of ClearLoadbalancerUUIDIfMatches.
func (mr *MockIClusterRepositoryMockRecorder) ClearLoadbalancerUUIDIfMatches(ctx, clusterUUID, loadBalancerUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearLoadbalancerUUIDIfMatches", reflect.TypeOf((*MockIClusterRepository)(nil).ClearLoadbalancerUUIDIfMatches), ctx, clusterUUID, loadBalancerUUID)
}

// ClusterNameExists mocks base method.
func (m *MockIClusterRepository) ClusterNameExists(ctx context.Context, projectID, clusterName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterNameExists", ctx, projectID, clusterName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterNameExists indicates an expected call of ClusterNameExists.
func (mr *MockIClusterRepositoryMockRecorder) ClusterNameExists(ctx, projectID, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterNameExists", reflect.TypeOf((*MockIClusterRepository)(nil).ClusterNameExists), ctx, projectID, clusterName)
}

// CreateCluster mocks base method.
func (m *MockIClusterRepository) CreateCluster(ctx context.Context, cluster *model.Cluster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCluster", ctx, cluster)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCluster indicates an expected call of CreateCluster.
func (mr *MockIClusterRepositoryMockRecorder) CreateCluster(ctx, cluster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCluster", reflect.TypeOf((*MockIClusterRepository)(nil).CreateCluster), ctx, cluster)
}

// DeleteUpdateCluster mocks base method.
func (m *MockIClusterRepository) DeleteUpdateCluster(ctx context.Context, cluster *model.Cluster, clusterUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUpdateCluster", ctx, cluster, clusterUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUpdateCluster indicates an expected call of DeleteUpdateCluster.
func (mr *MockIClusterRepositoryMockRecorder) DeleteUpdateCluster(ctx, cluster, clusterUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUpdateCluster", reflect.TypeOf((*MockIClusterRepository)(nil).DeleteUpdateCluster), ctx, cluster, clusterUUID)
}

// GetClusterByUUID mocks base method.
func (m *MockIClusterRepository) GetClusterByUUID(ctx context.Context, uuid string) (*model.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterByUUID", ctx, uuid)
	ret0, _ := ret[0].(*model.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterByUUID indicates an expected call of GetClusterByUUID.
func (mr *MockIClusterRepositoryMockRecorder) GetClusterByUUID(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterByUUID", reflect.TypeOf((*MockIClusterRepository)(nil).GetClusterByUUID), ctx, uuid)
}

// GetClustersByProjectId mocks base method.
func (m *MockIClusterRepository) GetClustersByProjectId(ctx context.Context, projectId string) ([]model.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClustersByProjectId", ctx, projectId)
	ret0, _ := ret[0].([]model.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClustersByProjectId indicates an expected call of GetClustersByProjectId.
func (mr *MockIClusterRepositoryMockRecorder) GetClustersByProjectId(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClustersByProjectId", reflect.TypeOf((*MockIClusterRepository)(nil).GetClustersByProjectId), ctx, projectId)
}

// UpdateCluster mocks base method.
func (m *MockIClusterRepository) UpdateCluster(ctx context.Context, cluster *model.Cluster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCluster", ctx, cluster)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCluster indicates an expected call of UpdateCluster.
func (mr *MockIClusterRepositoryMockRecorder) UpdateCluster(ctx, cluster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCluster", reflect.TypeOf((*MockIClusterRepository)(nil).UpdateCluster), ctx, cluster)
}

// MockIJobsRepository is a mock of IJobsRepository interface.
type MockIJobsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIJobsRepositoryMockRecorder
	isgomock struct{}
}

// MockIJobsRepositoryMockRecorder is the mock recorder for MockIJobsRepository.
type MockIJobsRepositoryMockRecorder struct {
	mock *MockIJobsRepository
}

// NewMockIJobsRepository creates a new mock instance.
func NewMockIJobsRepository(ctrl *gomock.Controller) *MockIJobsRepository {
	mock := &MockIJobsRepository{ctrl: ctrl}
	mock.recorder = &MockIJobsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIJobsRepository) EXPECT() *MockIJobsRepositoryMockRecorder {
	return m.recorder
}

// CreateJob mocks base method.
func (m *MockIJobsRepository) CreateJob(ctx context.Context, job *model.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockIJobsRepositoryMockRecorder) CreateJob(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockIJobsRepository)(nil).CreateJob), ctx, job)
}

// GetJobByIdempotencyKey mocks base method.
func (m *MockIJobsRepository) GetJobByIdempotencyKey(ctx context.Context, key string) (*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobByIdempotencyKey indicates an expected call of GetJobByIdempotencyKey.
func (mr *MockIJobsRepositoryMockRecorder) GetJobByIdempotencyKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobByIdempotencyKey", reflect.TypeOf((*MockIJobsRepository)(nil).GetJobByIdempotencyKey), ctx, key)
}

// GetJobByUUID mocks base method.
func (m *MockIJobsRepository) GetJobByUUID(ctx context.Context, jobUUID string) (*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobByUUID", ctx, jobUUID)
	ret0, _ := ret[0].(*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobByUUID indicates an expected call of GetJobByUUID.
func (mr *MockIJobsRepositoryMockRecorder) GetJobByUUID(ctx, jobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobByUUID", reflect.TypeOf((*MockIJobsRepository)(nil).GetJobByUUID), ctx, jobUUID)
}

// MarkJobFailed mocks base method.
func (m *MockIJobsRepository) MarkJobFailed(ctx context.Context, jobUUID, lastErr string, nextRunAt time.Time, attempts int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkJobFailed", ctx, jobUUID, lastErr, nextRunAt, attempts)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkJobFailed indicates an expected call of MarkJobFailed.
func (mr *MockIJobsRepositoryMockRecorder) MarkJobFailed(ctx, jobUUID, lastErr, nextRunAt, attempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkJobFailed", reflect.TypeOf((*MockIJobsRepository)(nil).MarkJobFailed), ctx, jobUUID, lastErr, nextRunAt, attempts)
}

// MarkJobQueued mocks base method.
func (m *MockIJobsRepository) MarkJobQueued(ctx context.Context, jobUUID string, nextRunAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkJobQueued", ctx, jobUUID, nextRunAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkJobQueued indicates an expected call of MarkJobQueued.
func (mr *MockIJobsRepositoryMockRecorder) MarkJobQueued(ctx, jobUUID, nextRunAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkJobQueued", reflect.TypeOf((*MockIJobsRepository)(nil).MarkJobQueued), ctx, jobUUID, nextRunAt)
}

// MarkJobSucceeded mocks base method.
func (m *MockIJobsRepository) MarkJobSucceeded(ctx context.Context, jobUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkJobSucceeded", ctx, jobUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkJobSucceeded indicates an expected call of MarkJobSucceeded.
func (mr *MockIJobsRepositoryMockRecorder) MarkJobSucceeded(ctx, jobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkJobSucceeded", reflect.TypeOf((*MockIJobsRepository)(nil).MarkJobSucceeded), ctx, jobUUID)
}

// RetireIdempotencyKey mocks base method.
func (m *MockIJobsRepository) RetireIdempotencyKey(ctx context.Context, jobUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetireIdempotencyKey", ctx, jobUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetireIdempotencyKey indicates an expected call of RetireIdempotencyKey.
func (mr *MockIJobsRepositoryMockRecorder) RetireIdempotencyKey(ctx, jobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetireIdempotencyKey", reflect.TypeOf((*MockIJobsRepository)(nil).RetireIdempotencyKey), ctx, jobUUID)
}

// TouchJobLock mocks base method.
func (m *MockIJobsRepository) TouchJobLock(ctx context.Context, jobUUID, lockedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchJobLock", ctx, jobUUID, lockedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchJobLock indicates an expected call of TouchJobLock.
func (mr *MockIJobsRepositoryMockRecorder) TouchJobLock(ctx, jobUUID, lockedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchJobLock", reflect.TypeOf((*MockIJobsRepository)(nil).TouchJobLock), ctx, jobUUID, lockedBy)
}

// TryMarkJobStarted mocks base method.
func (m *MockIJobsRepository) TryMarkJobStarted(ctx context.Context, jobUUID, lockedBy string, staleAfter time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryMarkJobStarted", ctx, jobUUID, lockedBy, staleAfter)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryMarkJobStarted indicates an expected call of TryMarkJobStarted.
func (mr *MockIJobsRepositoryMockRecorder) TryMarkJobStarted(ctx, jobUUID, lockedBy, staleAfter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryMarkJobStarted", reflect.TypeOf((*MockIJobsRepository)(nil).TryMarkJobStarted), ctx, jobUUID, lockedBy, staleAfter)
}

// MockIAuditLogRepository is a mock of IAuditLogRepository interface.
type MockIAuditLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAuditLogRepositoryMockRecorder
	isgomock struct{}
}

// MockIAuditLogRepositoryMockRecorder is the mock recorder for MockIAuditLogRepository.
type MockIAuditLogRepositoryMockRecorder struct {
	mock *MockIAuditLogRepository
}

// NewMockIAuditLogRepository creates a new mock instance.
func NewMockIAuditLogRepository(ctrl *gomock.Controller) *MockIAuditLogRepository {
	mock := &MockIAuditLogRepository{ctrl: ctrl}
	mock.recorder = &MockIAuditLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuditLogRepository) EXPECT() *MockIAuditLogRepositoryMockRecorder {
	return m.recorder
}

// CreateAuditLog mocks base method.
func (m *MockIAuditLogRepository) CreateAuditLog(ctx context.Context, auditLog *model.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditLog", ctx, auditLog)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuditLog indicates an expected call of CreateAuditLog.
func (mr *MockIAuditLogRepositoryMockRecorder) CreateAuditLog(ctx, auditLog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditLog", reflect.TypeOf((*MockIAuditLogRepository)(nil).CreateAuditLog), ctx, auditLog)
}

// MockIKubeconfigRepository is a mock of IKubeconfigRepository interface.
type MockIKubeconfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIKubeconfigRepositoryMockRecorder
	isgomock struct{}
}

// MockIKubeconfigRepositoryMockRecorder is the mock recorder for MockIKubeconfigRepository.
type MockIKubeconfigRepositoryMockRecorder struct {
	mock *MockIKubeconfigRepository
}

// NewMockIKubeconfigRepository creates a new mock instance.
func NewMockIKubeconfigRepository(ctrl *gomock.Controller) *MockIKubeconfigRepository {
	mock := &MockIKubeconfigRepository{ctrl: ctrl}
	mock.recorder = &MockIKubeconfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKubeconfigRepository) EXPECT() *MockIKubeconfigRepositoryMockRecorder {
	return m.recorder
}

// CreateKubeconfig mocks base method.
func (m *MockIKubeconfigRepository) CreateKubeconfig(ctx context.Context, kubeconfig *model.Kubeconfigs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKubeconfig", ctx, kubeconfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKubeconfig indicates an expected call of CreateKubeconfig.
func (mr *MockIKubeconfigRepositoryMockRecorder) CreateKubeconfig(ctx, kubeconfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKubeconfig", reflect.TypeOf((*MockIKubeconfigRepository)(nil).CreateKubeconfig), ctx, kubeconfig)
}

// GetKubeconfigByUUID mocks base method.
func (m *MockIKubeconfigRepository) GetKubeconfigByUUID(ctx context.Context, clusterUUID string) (*model.Kubeconfigs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKubeconfigByUUID", ctx, clusterUUID)
	ret0, _ := ret[0].(*model.Kubeconfigs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKubeconfigByUUID indicates an expected call of GetKubeconfigByUUID.
func (mr *MockIKubeconfigRepositoryMockRecorder) GetKubeconfigByUUID(ctx, clusterUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubeconfigByUUID", reflect.TypeOf((*MockIKubeconfigRepository)(nil).GetKubeconfigByUUID), ctx, clusterUUID)
}

// UpdateKubeconfig mocks base method.
func (m *MockIKubeconfigRepository) UpdateKubeconfig(ctx context.Context, clusterUUID, kubeConfig string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKubeconfig", ctx, clusterUUID, kubeConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKubeconfig indicates an expected call of UpdateKubeconfig.
func (mr *MockIKubeconfigRepositoryMockRecorder) UpdateKubeconfig(ctx, clusterUUID, kubeConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKubeconfig", reflect.TypeOf((*MockIKubeconfigRepository)(nil).UpdateKubeconfig), ctx, clusterUUID, kubeConfig)
}

// MockINodeGroupsRepository is a mock of INodeGroupsRepository interface.
type MockINodeGroupsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockINodeGroupsRepositoryMockRecorder
	isgomock struct{}
}

// MockINodeGroupsRepositoryMockRecorder is the mock recorder for MockINodeGroupsRepository.
type MockINodeGroupsRepositoryMockRecorder struct {
	mock *MockINodeGroupsRepository
}

// NewMockINodeGroupsRepository creates a new mock instance.
func NewMockINodeGroupsRepository(ctrl *gomock.Controller) *MockINodeGroupsRepository {
	mock := &MockINodeGroupsRepository{ctrl: ctrl}
	mock.recorder = &MockINodeGroupsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINodeGroupsRepository) EXPECT() *MockINodeGroupsRepositoryMockRecorder {
	return m.recorder
}

// CreateNodeGroups mocks base method.
func (m *MockINodeGroupsRepository) CreateNodeGroups(ctx context.Context, nodeGroups *model.NodeGroups) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodeGroups", ctx, nodeGroups)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNodeGroups indicates an expected call of CreateNodeGroups.
func (mr *MockINodeGroupsRepositoryMockRecorder) CreateNodeGroups(ctx, nodeGroups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodeGroups", reflect.TypeOf((*MockINodeGroupsRepository)(nil).CreateNodeGroups), ctx, nodeGroups)
}

// GetClusterProjectUUIDByNodeGroupUUID mocks base method.
func (m *MockINodeGroupsRepository) GetClusterProjectUUIDByNodeGroupUUID(ctx context.Context, nodeGroupUUID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterProjectUUIDByNodeGroupUUID", ctx, nodeGroupUUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterProjectUUIDByNodeGroupUUID indicates an expected call of GetClusterProjectUUIDByNodeGroupUUID.
func (mr *MockINodeGroupsRepositoryMockRecorder) GetClusterProjectUUIDByNodeGroupUUID(ctx, nodeGroupUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterProjectUUIDByNodeGroupUUID", reflect.TypeOf((*MockINodeGroupsRepository)(nil).GetClusterProjectUUIDByNodeGroupUUID), ctx, nodeGroupUUID)
}

// GetNodeGroupByUUID mocks base method.
func (m *MockINodeGroupsRepository) GetNodeGroupByUUID(ctx context.Context, uuid string) (*model.NodeGroups, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeGroupByUUID", ctx, uuid)
	ret0, _ := ret[0].(*model.NodeGroups)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeGroupByUUID indicates an expected call of GetNodeGroupByUUID.
func (mr *MockINodeGroupsRepositoryMockRecorder) GetNodeGroupByUUID(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeGroupByUUID", reflect.TypeOf((*MockINodeGroupsRepository)(nil).GetNodeGroupByUUID), ctx, uuid)
}

// GetNodeGroupsByClusterUUID mocks base method.
func (m *MockINodeGroupsRepository) GetNodeGroupsByClusterUUID(ctx context.Context, uuid, nodeType, nodeGroupStatus string) ([]model.NodeGroups, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeGroupsByClusterUUID", ctx, uuid, nodeType, nodeGroupStatus)
	ret0, _ := ret[0].([]model.NodeGroups)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeGroupsByClusterUUID indicates an expected call of GetNodeGroupsByClusterUUID.
func (mr *MockINodeGroupsRepositoryMockRecorder) GetNodeGroupsByClusterUUID(ctx, uuid, nodeType, nodeGroupStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeGroupsByClusterUUID", reflect.TypeOf((*MockINodeGroupsRepository)(nil).GetNodeGroupsByClusterUUID), ctx, uuid, nodeType, nodeGroupStatus)
}

// UpdateNodeGroups mocks base method.
func (m *MockINodeGroupsRepository) UpdateNodeGroups(ctx context.Context, nodeGroups *model.NodeGroups) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNodeGroups", ctx, nodeGroups)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNodeGroups indicates an expected call of UpdateNodeGroups.
func (mr *MockINodeGroupsRepositoryMockRecorder) UpdateNodeGroups(ctx, nodeGroups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNodeGroups", reflect.TypeOf((*MockINodeGroupsRepository)(nil).UpdateNodeGroups), ctx, nodeGroups)
}

// MockIResourcesRepository is a mock of IResourcesRepository interface.
type MockIResourcesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIResourcesRepositoryMockRecorder
	isgomock struct{}
}

// MockIResourcesRepositoryMockRecorder is the mock recorder for MockIResourcesRepository.
type MockIResourcesRepositoryMockRecorder struct {
	mock *MockIResourcesRepository
}

// NewMockIResourcesRepository creates a new mock instance.
func NewMockIResourcesRepository(ctrl *gomock.Controller) *MockIResourcesRepository {
	mock := &MockIResourcesRepository{ctrl: ctrl}
	mock.recorder = &MockIResourcesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIResourcesRepository) EXPECT() *MockIResourcesRepositoryMockRecorder {
	return m.recorder
}

// CreateResource mocks base method.
func (m *MockIResourcesRepository) CreateResource(ctx context.Context, resource *model.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResource", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateResource indicates an expected call of CreateResource.
func (mr *MockIResourcesRepositoryMockRecorder) CreateResource(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResource", reflect.TypeOf((*MockIResourcesRepository)(nil).CreateResource), ctx, resource)
}

// DeleteResourcesByClusterTypeAndUUID mocks base method.
func (m *MockIResourcesRepository) DeleteResourcesByClusterTypeAndUUID(ctx context.Context, clusterUUID, resourceType, resourceUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResourcesByClusterTypeAndUUID", ctx, clusterUUID, resourceType, resourceUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResourcesByClusterTypeAndUUID indicates an expected call of DeleteResourcesByClusterTypeAndUUID.
func (mr *MockIResourcesRepositoryMockRecorder) DeleteResourcesByClusterTypeAndUUID(ctx, clusterUUID, resourceType, resourceUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResourcesByClusterTypeAndUUID", reflect.TypeOf((*MockIResourcesRepository)(nil).DeleteResourcesByClusterTypeAndUUID), ctx, clusterUUID, resourceType, resourceUUID)
}

// GetResourceByClusterUUID mocks base method.
func (m *MockIResourcesRepository) GetResourceByClusterUUID(ctx context.Context, clusterUUID, resourceType string) ([]model.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceByClusterUUID", ctx, clusterUUID, resourceType)
	ret0, _ := ret[0].([]model.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceByClusterUUID indicates an expected call of GetResourceByClusterUUID.
func (mr *MockIResourcesRepositoryMockRecorder) GetResourceByClusterUUID(ctx, clusterUUID, resourceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceByClusterUUID", reflect.TypeOf((*MockIResourcesRepository)(nil).GetResourceByClusterUUID), ctx, clusterUUID, resourceType)
}

// SetResourceUUIDByClusterAndType mocks base method.
func (m *MockIResourcesRepository) SetResourceUUIDByClusterAndType(ctx context.Context, clusterUUID, resourceType, resourceUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetResourceUUIDByClusterAndType", ctx, clusterUUID, resourceType, resourceUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetResourceUUIDByClusterAndType indicates an expected call of SetResourceUUIDByClusterAndType.
func (mr *MockIResourcesRepositoryMockRecorder) SetResourceUUIDByClusterAndType(ctx, clusterUUID, resourceType, resourceUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResourceUUIDByClusterAndType", reflect.TypeOf((*MockIResourcesRepository)(nil).SetResourceUUIDByClusterAndType), ctx, clusterUUID, resourceType, resourceUUID)
}

// MockIErrorRepository is a mock of IErrorRepository interface.
type MockIErrorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIErrorRepositoryMockRecorder
	isgomock struct{}
}

// MockIErrorRepositoryMockRecorder is the mock recorder for MockIErrorRepository.
type MockIErrorRepositoryMockRecorder struct {
	mock *MockIErrorRepository
}

// NewMockIErrorRepository creates a new mock instance.
func NewMockIErrorRepository(ctrl *gomock.Controller) *MockIErrorRepository {
	mock := &MockIErrorRepository{ctrl: ctrl}
	mock.recorder = &MockIErrorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIErrorRepository) EXPECT() *MockIErrorRepositoryMockRecorder {
	return m.recorder
}

// CreateError mocks base method.
func (m *MockIErrorRepository) CreateError(ctx context.Context, err *model.Error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateError", ctx, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateError indicates an expected call of CreateError.
func (mr *MockIErrorRepositoryMockRecorder) CreateError(ctx, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateError", reflect.TypeOf((*MockIErrorRepository)(nil).CreateError), ctx, err)
}

// GetErrorsByClusterUUID mocks base method.
func (m *MockIErrorRepository) GetErrorsByClusterUUID(ctx context.Context, clusterUUID string) ([]model.Error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrorsByClusterUUID", ctx, clusterUUID)
	ret0, _ := ret[0].([]model.Error)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetErrorsByClusterUUID indicates an expected call of GetErrorsByClusterUUID.
func (mr *MockIErrorRepositoryMockRecorder) GetErrorsByClusterUUID(ctx, clusterUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrorsByClusterUUID", reflect.TypeOf((*MockIErrorRepository)(nil).GetErrorsByClusterUUID), ctx, clusterUUID)
}
