ALTER TABLE `clusters`
  ADD COLUMN IF NOT EXISTS `application_credential_secret_enc` text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `create_request` json DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `create_state` enum('INITIAL','LOADBALANCER','FLOATING_IP','SECURITY_GROUPS','SERVER_GROUPS','PORTS','COMPUTES','DNS','KUBECONFIG','COMPLETED') DEFAULT 'INITIAL';

