// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmindtech/vke/internal/service (interfaces: IComputeService,INetworkService,ILoadbalancerService,ICloudflareService,IIdentityService,INodeGroupsService)
//
// Generated by this command:
//
//	mockgen -destination=service_mocks_test.go -package=service github.com/vmindtech/vke/internal/service IComputeService,INetworkService,ILoadbalancerService,ICloudflareService,IIdentityService,INodeGroupsService
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	request "github.com/vmindtech/vke/internal/dto/request"
	resource "github.com/vmindtech/vke/internal/dto/resource"
	gomock "go.uber.org/mock/gomock"
)

// MockIComputeService is a mock of IComputeService interface.
type MockIComputeService struct {
	ctrl     *gomock.Controller
	recorder *MockIComputeServiceMockRecorder
	isgomock struct{}
}

// MockIComputeServiceMockRecorder is the mock recorder for MockIComputeService.
type MockIComputeServiceMockRecorder struct {
	mock *MockIComputeService
}

// NewMockIComputeService creates a new mock instance.
func NewMockIComputeService(ctrl *gomock.Controller) *MockIComputeService {
	mock := &MockIComputeService{ctrl: ctrl}
	mock.recorder = &MockIComputeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIComputeService) EXPECT() *MockIComputeServiceMockRecorder {
	return m.recorder
}

// CreateCompute mocks base method.
func (m *MockIComputeService) CreateCompute(ctx context.Context, authToken string, req request.CreateComputeRequest) (resource.CreateComputeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCompute", ctx, authToken, req)
	ret0, _ := ret[0].(resource.CreateComputeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCompute indicates an expected call of CreateCompute.
func (mr *MockIComputeServiceMockRecorder) CreateCompute(ctx, authToken, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCompute", reflect.TypeOf((*MockIComputeService)(nil).CreateCompute), ctx, authToken, req)
}

// CreateServerGroup mocks base method.
func (m *MockIComputeService) CreateServerGroup(ctx context.Context, authToken string, req request.CreateServerGroupRequest) (resource.ServerGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServerGroup", ctx, authToken, req)
	ret0, _ := ret[0].(resource.ServerGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServerGroup indicates an expected call of CreateServerGroup.
func (mr *MockIComputeServiceMockRecorder) CreateServerGroup(ctx, authToken, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServerGroup", reflect.TypeOf((*MockIComputeService)(nil).CreateServerGroup), ctx, authToken, req)
}

// DeleteCompute mocks base method.
func (m *MockIComputeService) DeleteCompute(ctx context.Context, authToken, serverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCompute", ctx, authToken, serverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCompute indicates an expected call of DeleteCompute.
func (mr *MockIComputeServiceMockRecorder) DeleteCompute(ctx, authToken, serverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCompute", reflect.TypeOf((*MockIComputeService)(nil).DeleteCompute), ctx, authToken, serverID)
}

// DeleteServer mocks base method.
func (m *MockIComputeService) DeleteServer(ctx context.Context, authToken, serverID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServer", ctx, authToken, serverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServer indicates an expected call of DeleteServer.
func (mr *MockIComputeServiceMockRecorder) DeleteServer(ctx, authToken, serverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServer", reflect.TypeOf((*MockIComputeService)(nil).DeleteServer), ctx, authToken, serverID)
}

// DeleteServerGroup mocks base method.
func (m *MockIComputeService) DeleteServerGroup(ctx context.Context, authToken, clusterServerGroupUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServerGroup", ctx, authToken, clusterServerGroupUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServerGroup indicates an expected call of DeleteServerGroup.
func (mr *MockIComputeServiceMockRecorder) DeleteServerGroup(ctx, authToken, clusterServerGroupUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServerGroup", reflect.TypeOf((*MockIComputeService)(nil).DeleteServerGroup), ctx, authToken, clusterServerGroupUUID)
}

// GetClusterFlavor mocks base method.
func (m *MockIComputeService) GetClusterFlavor(ctx context.Context, authToken, clusterUUID string) ([]resource.Flavor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterFlavor", ctx, authToken, clusterUUID)
	ret0, _ := ret[0].([]resource.Flavor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterFlavor indicates an expected call of GetClusterFlavor.
func (mr *MockIComputeServiceMockRecorder) GetClusterFlavor(ctx, authToken, clusterUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterFlavor", reflect.TypeOf((*MockIComputeService)(nil).GetClusterFlavor), ctx, authToken, clusterUUID)
}

// GetCountOfServerFromServerGroup mocks base method.
func (m *MockIComputeService) GetCountOfServerFromServerGroup(ctx context.Context, authToken, serverGroupID, projectUUID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountOfServerFromServerGroup", ctx, authToken, serverGroupID, projectUUID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountOfServerFromServerGroup indicates an expected call of GetCountOfServerFromServerGroup.
func (mr *MockIComputeServiceMockRecorder) GetCountOfServerFromServerGroup(ctx, authToken, serverGroupID, projectUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountOfServerFromServerGroup", reflect.TypeOf((*MockIComputeService)(nil).GetCountOfServerFromServerGroup), ctx, authToken, serverGroupID, projectUUID)
}

// GetInstances mocks base method.
func (m *MockIComputeService) GetInstances(ctx context.Context, authToken, nodeGroupUUID string) ([]resource.Servers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstances", ctx, authToken, nodeGroupUUID)
	ret0, _ := ret[0].([]resource.Servers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstances indicates an expected call of GetInstances.
func (mr *MockIComputeServiceMockRecorder) GetInstances(ctx, authToken, nodeGroupUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstances", reflect.TypeOf((*MockIComputeService)(nil).GetInstances), ctx, authToken, nodeGroupUUID)
}

// GetInstancesDetail mocks base method.
func (m *MockIComputeService) GetInstancesDetail(ctx context.Context, authToken, serverID string) (resource.OpenstacServersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstancesDetail", ctx, authToken, serverID)
	ret0, _ := ret[0].(resource.OpenstacServersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstancesDetail indicates an expected call of GetInstancesDetail.
func (mr *MockIComputeServiceMockRecorder) GetInstancesDetail(ctx, authToken, serverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstancesDetail", reflect.TypeOf((*MockIComputeService)(nil).GetInstancesDetail), ctx, authToken, serverID)
}

// GetServerGroup mocks base method.
func (m *MockIComputeService) GetServerGroup(ctx context.Context, authToken, serverGroupID string) (resource.GetServerGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerGroup", ctx, authToken, serverGroupID)
	ret0, _ := ret[0].(resource.GetServerGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerGroup indicates an expected call of GetServerGroup.
func (mr *MockIComputeServiceMockRecorder) GetServerGroup(ctx, authToken, serverGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerGroup", reflect.TypeOf((*MockIComputeService)(nil).GetServerGroup), ctx, authToken, serverGroupID)
}

// GetServerGroupMemberList mocks base method.
func (m *MockIComputeService) GetServerGroupMemberList(ctx context.Context, authToken, ServerGroupID string) (resource.GetServerGroupMemberListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerGroupMemberList", ctx, authToken, ServerGroupID)
	ret0, _ := ret[0].(resource.GetServerGroupMemberListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerGroupMemberList indicates an expected call of GetServerGroupMemberList.
func (mr *MockIComputeServiceMockRecorder) GetServerGroupMemberList(ctx, authToken, ServerGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerGroupMemberList", reflect.TypeOf((*MockIComputeService)(nil).GetServerGroupMemberList), ctx, authToken, ServerGroupID)
}

// MockINetworkService is a mock of INetworkService interface.
type MockINetworkService struct {
	ctrl     *gomock.Controller
	recorder *MockINetworkServiceMockRecorder
	isgomock struct{}
}

// MockINetworkServiceMockRecorder is the mock recorder for MockINetworkService.
type MockINetworkServiceMockRecorder struct {
	mock *MockINetworkService
}

// NewMockINetworkService creates a new mock instance.
func NewMockINetworkService(ctrl *gomock.Controller) *MockINetworkService {
	mock := &MockINetworkService{ctrl: ctrl}
	mock.recorder = &MockINetworkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINetworkService) EXPECT() *MockINetworkServiceMockRecorder {
	return m.recorder
}

// CreateFloatingIP mocks base method.
func (m *MockINetworkService) CreateFloatingIP(ctx context.Context, authToken string, req request.CreateFloatingIPRequest) (resource.CreateFloatingIPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFloatingIP", ctx, authToken, req)
	ret0, _ := ret[0].(resource.CreateFloatingIPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFloatingIP indicates an expected call of CreateFloatingIP.
func (mr *MockINetworkServiceMockRecorder) CreateFloatingIP(ctx, authToken, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFloatingIP", reflect.TypeOf((*MockINetworkService)(nil).CreateFloatingIP), ctx, authToken, req)
}

// CreateNetworkPort mocks base method.
func (m *MockINetworkService) CreateNetworkPort(ctx context.Context, authToken string, req request.CreateNetworkPortRequest) (resource.CreateNetworkPortResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetworkPort", ctx, authToken, req)
	ret0, _ := ret[0].(resource.CreateNetworkPortResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetworkPort indicates an expected call of CreateNetworkPort.
func (mr *MockINetworkServiceMockRecorder) CreateNetworkPort(ctx, authToken, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetworkPort", reflect.TypeOf((*MockINetworkService)(nil).CreateNetworkPort), ctx, authToken, req)
}

// CreateSecurityGroup mocks base method.
func (m *MockINetworkService) CreateSecurityGroup(ctx context.Context, authToken string, req request.CreateSecurityGroupRequest) (resource.CreateSecurityGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecurityGroup", ctx, authToken, req)
	ret0, _ := ret[0].(resource.CreateSecurityGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecurityGroup indicates an expected call of CreateSecurityGroup.
func (mr *MockINetworkServiceMockRecorder) CreateSecurityGroup(ctx, authToken, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecurityGroup", reflect.TypeOf((*MockINetworkService)(nil).CreateSecurityGroup), ctx, authToken, req)
}

// CreateSecurityGroupRuleForIP mocks base method.
func (m *MockINetworkService) CreateSecurityGroupRuleForIP(ctx context.Context, authToken string, req request.CreateSecurityGroupRuleForIpRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecurityGroupRuleForIP", ctx, authToken, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecurityGroupRuleForIP indicates an expected call of CreateSecurityGroupRuleForIP.
func (mr *MockINetworkServiceMockRecorder) CreateSecurityGroupRuleForIP(ctx, authToken, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecurityGroupRuleForIP", reflect.TypeOf((*MockINetworkService)(nil).CreateSecurityGroupRuleForIP), ctx, authToken, req)
}

// CreateSecurityGroupRuleForSG mocks base method.
func (m *MockINetworkService) CreateSecurityGroupRuleForSG(ctx context.Context, authToken string, req request.CreateSecurityGroupRuleForSgRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecurityGroupRuleForSG", ctx, authToken, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecurityGroupRuleForSG indicates an expected call of CreateSecurityGroupRuleForSG.
func (mr *MockINetworkServiceMockRecorder) CreateSecurityGroupRuleForSG(ctx, authToken, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecurityGroupRuleForSG", reflect.TypeOf((*MockINetworkService)(nil).CreateSecurityGroupRuleForSG), ctx, authToken, req)
}

// DeleteFloatingIP mocks base method.
func (m *MockINetworkService) DeleteFloatingIP(ctx context.Context, authToken, floatingIPID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFloatingIP", ctx, authToken, floatingIPID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFloatingIP indicates an expected call of DeleteFloatingIP.
func (mr *MockINetworkServiceMockRecorder) DeleteFloatingIP(ctx, authToken, floatingIPID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFloatingIP", reflect.TypeOf((*MockINetworkService)(nil).DeleteFloatingIP), ctx, authToken, floatingIPID)
}

// DeleteNetworkPort mocks base method.
func (m *MockINetworkService) DeleteNetworkPort(ctx context.Context, authToken, portID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetworkPort", ctx, authToken, portID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetworkPort indicates an expected call of DeleteNetworkPort.
func (mr *MockINetworkServiceMockRecorder) DeleteNetworkPort(ctx, authToken, portID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetworkPort", reflect.TypeOf((*MockINetworkService)(nil).DeleteNetworkPort), ctx, authToken, portID)
}

// DeleteSecurityGroup mocks base method.
func (m *MockINetworkService) DeleteSecurityGroup(ctx context.Context, authToken, clusterSecurityGroupId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecurityGroup", ctx, authToken, clusterSecurityGroupId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecurityGroup indicates an expected call of DeleteSecurityGroup.
func (mr *MockINetworkServiceMockRecorder) DeleteSecurityGroup(ctx, authToken, clusterSecurityGroupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecurityGroup", reflect.TypeOf((*MockINetworkService)(nil).DeleteSecurityGroup), ctx, authToken, clusterSecurityGroupId)
}

// GetComputeNetworkPorts mocks base method.
func (m *MockINetworkService) GetComputeNetworkPorts(ctx context.Context, authToken, instanceID string) (resource.NetworkPortsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComputeNetworkPorts", ctx, authToken, instanceID)
	ret0, _ := ret[0].(resource.NetworkPortsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComputeNetworkPorts indicates an expected call of GetComputeNetworkPorts.
func (mr *MockINetworkServiceMockRecorder) GetComputeNetworkPorts(ctx, authToken, instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComputeNetworkPorts", reflect.TypeOf((*MockINetworkService)(nil).GetComputeNetworkPorts), ctx, authToken, instanceID)
}

// GetFloatingIP mocks base method.
func (m *MockINetworkService) GetFloatingIP(ctx context.Context, authToken, floatingIPID string) (resource.CreateFloatingIPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFloatingIP", ctx, authToken, floatingIPID)
	ret0, _ := ret[0].(resource.CreateFloatingIPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFloatingIP indicates an expected call of GetFloatingIP.
func (mr *MockINetworkServiceMockRecorder) GetFloatingIP(ctx, authToken, floatingIPID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFloatingIP", reflect.TypeOf((*MockINetworkService)(nil).GetFloatingIP), ctx, authToken, floatingIPID)
}

// GetNetworkID mocks base method.
func (m *MockINetworkService) GetNetworkID(ctx context.Context, authToken, subnetID string) (resource.GetNetworkIdResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkID", ctx, authToken, subnetID)
	ret0, _ := ret[0].(resource.GetNetworkIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkID indicates an expected call of GetNetworkID.
func (mr *MockINetworkServiceMockRecorder) GetNetworkID(ctx, authToken, subnetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkID", reflect.TypeOf((*MockINetworkService)(nil).GetNetworkID), ctx, authToken, subnetID)
}

// GetNetworkPort mocks base method.
func (m *MockINetworkService) GetNetworkPort(ctx context.Context, authToken, portID string) (resource.CreateNetworkPortResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkPort", ctx, authToken, portID)
	ret0, _ := ret[0].(resource.CreateNetworkPortResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkPort indicates an expected call of GetNetworkPort.
func (mr *MockINetworkServiceMockRecorder) GetNetworkPort(ctx, authToken, portID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkPort", reflect.TypeOf((*MockINetworkService)(nil).GetNetworkPort), ctx, authToken, portID)
}

// GetSecurityGroupByID mocks base method.
func (m *MockINetworkService) GetSecurityGroupByID(ctx context.Context, authToken, securityGroupID string) (resource.GetSecurityGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityGroupByID", ctx, authToken, securityGroupID)
	ret0, _ := ret[0].(resource.GetSecurityGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityGroupByID indicates an expected call of GetSecurityGroupByID.
func (mr *MockINetworkServiceMockRecorder) GetSecurityGroupByID(ctx, authToken, securityGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityGroupByID", reflect.TypeOf((*MockINetworkService)(nil).GetSecurityGroupByID), ctx, authToken, securityGroupID)
}

// GetSecurityGroupPorts mocks base method.
func (m *MockINetworkService) GetSecurityGroupPorts(ctx context.Context, authToken, securityGroupID string) (resource.NetworkPortsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityGroupPorts", ctx, authToken, securityGroupID)
	ret0, _ := ret[0].(resource.NetworkPortsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityGroupPorts indicates an expected call of GetSecurityGroupPorts.
func (mr *MockINetworkServiceMockRecorder) GetSecurityGroupPorts(ctx, authToken, securityGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityGroupPorts", reflect.TypeOf((*MockINetworkService)(nil).GetSecurityGroupPorts), ctx, authToken, securityGroupID)
}

// GetSubnetByID mocks base method.
func (m *MockINetworkService) GetSubnetByID(ctx context.Context, authToken, subnetID string) (resource.SubnetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetByID", ctx, authToken, subnetID)
	ret0, _ := ret[0].(resource.SubnetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetByID indicates an expected call of GetSubnetByID.
func (mr *MockINetworkServiceMockRecorder) GetSubnetByID(ctx, authToken, subnetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetByID", reflect.TypeOf((*MockINetworkService)(nil).GetSubnetByID), ctx, authToken, subnetID)
}

// ListSecurityGroupsByName mocks base method.
func (m *MockINetworkService) ListSecurityGroupsByName(ctx context.Context, authToken, name string) (resource.ListSecurityGroupsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSecurityGroupsByName", ctx, authToken, name)
	ret0, _ := ret[0].(resource.ListSecurityGroupsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecurityGroupsByName indicates an expected call of ListSecurityGroupsByName.
func (mr *MockINetworkServiceMockRecorder) ListSecurityGroupsByName(ctx, authToken, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecurityGroupsByName", reflect.TypeOf((*MockINetworkService)(nil).ListSecurityGroupsByName), ctx, authToken, name)
}

// ListSubnetByName mocks base method.
func (m *MockINetworkService) ListSubnetByName(ctx context.Context, subnetName, authToken string) (resource.ListSubnetByNameResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubnetByName", ctx, subnetName, authToken)
	ret0, _ := ret[0].(resource.ListSubnetByNameResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubnetByName indicates an expected call of ListSubnetByName.
func (mr *MockINetworkServiceMockRecorder) ListSubnetByName(ctx, subnetName, authToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubnetByName", reflect.TypeOf((*MockINetworkService)(nil).ListSubnetByName), ctx, subnetName, authToken)
}

// MockILoadbalancerService is a mock of ILoadbalancerService interface.
type MockILoadbalancerService struct {
	ctrl     *gomock.Controller
	recorder *MockILoadbalancerServiceMockRecorder
	isgomock struct{}
}

// MockILoadbalancerServiceMockRecorder is the mock recorder for MockILoadbalancerService.
type MockILoadbalancerServiceMockRecorder struct {
	mock *MockILoadbalancerService
}

// NewMockILoadbalancerService creates a new mock instance.
func NewMockILoadbalancerService(ctrl *gomock.Controller) *MockILoadbalancerService {
	mock := &MockILoadbalancerService{ctrl: ctrl}
	mock.recorder = &MockILoadbalancerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILoadbalancerService) EXPECT() *MockILoadbalancerServiceMockRecorder {
	return m.recorder
}

// CheckLoadBalancerDeletingListeners mocks base method.
func (m *MockILoadbalancerService) CheckLoadBalancerDeletingListeners(ctx context.Context, authToken, listenerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLoadBalancerDeletingListeners", ctx, authToken, listenerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckLoadBalancerDeletingListeners indicates an expected call of CheckLoadBalancerDeletingListeners.
func (mr *MockILoadbalancerServiceMockRecorder) CheckLoadBalancerDeletingListeners(ctx, authToken, listenerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLoadBalancerDeletingListeners", reflect.TypeOf((*MockILoadbalancerService)(nil).CheckLoadBalancerDeletingListeners), ctx, authToken, listenerID)
}

// CheckLoadBalancerDeletingPools mocks base method.
func (m *MockILoadbalancerService) CheckLoadBalancerDeletingPools(ctx context.Context, authToken, poolID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLoadBalancerDeletingPools", ctx, authToken, poolID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckLoadBalancerDeletingPools indicates an expected call of CheckLoadBalancerDeletingPools.
func (mr *MockILoadbalancerServiceMockRecorder) CheckLoadBalancerDeletingPools(ctx, authToken, poolID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLoadBalancerDeletingPools", reflect.TypeOf((*MockILoadbalancerService)(nil).CheckLoadBalancerDeletingPools), ctx, authToken, poolID)
}

// CheckLoadBalancerOperationStatus mocks base method.
func (m *MockILoadbalancerService) CheckLoadBalancerOperationStatus(ctx context.Context, authToken, loadBalancerID string) (resource.ListLoadBalancerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLoadBalancerOperationStatus", ctx, authToken, loadBalancerID)
	ret0, _ := ret[0].(resource.ListLoadBalancerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLoadBalancerOperationStatus indicates an expected call of CheckLoadBalancerOperationStatus.
func (mr *MockILoadbalancerServiceMockRecorder) CheckLoadBalancerOperationStatus(ctx, authToken, loadBalancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLoadBalancerOperationStatus", reflect.TypeOf((*MockILoadbalancerService)(nil).CheckLoadBalancerOperationStatus), ctx, authToken, loadBalancerID)
}

// CheckLoadBalancerStatus mocks base method.
func (m *MockILoadbalancerService) CheckLoadBalancerStatus(ctx context.Context, authToken, loadBalancerID string) (resource.ListLoadBalancerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLoadBalancerStatus", ctx, authToken, loadBalancerID)
	ret0, _ := ret[0].(resource.ListLoadBalancerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLoadBalancerStatus indicates an expected call of CheckLoadBalancerStatus.
func (mr *MockILoadbalancerServiceMockRecorder) CheckLoadBalancerStatus(ctx, authToken, loadBalancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLoadBalancerStatus", reflect.TypeOf((*MockILoadbalancerService)(nil).CheckLoadBalancerStatus), ctx, authToken, loadBalancerID)
}

// CreateHealthHTTPMonitor mocks base method.
func (m *MockILoadbalancerService) CreateHealthHTTPMonitor(ctx context.Context, authToken string, req request.CreateHealthMonitorHTTPRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHealthHTTPMonitor", ctx, authToken, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateHealthHTTPMonitor indicates an expected call of CreateHealthHTTPMonitor.
func (mr *MockILoadbalancerServiceMockRecorder) CreateHealthHTTPMonitor(ctx, authToken, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHealthHTTPMonitor", reflect.TypeOf((*MockILoadbalancerService)(nil).CreateHealthHTTPMonitor), ctx, authToken, req)
}

// CreateHealthTCPMonitor mocks base method.
func (m *MockILoadbalancerService) CreateHealthTCPMonitor(ctx context.Context, authToken string, req request.CreateHealthMonitorTCPRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHealthTCPMonitor", ctx, authToken, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateHealthTCPMonitor indicates an expected call of CreateHealthTCPMonitor.
func (mr *MockILoadbalancerServiceMockRecorder) CreateHealthTCPMonitor(ctx, authToken, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHealthTCPMonitor", reflect.TypeOf((*MockILoadbalancerService)(nil).CreateHealthTCPMonitor), ctx, authToken, req)
}

// CreateListener mocks base method.
func (m *MockILoadbalancerService) CreateListener(ctx context.Context, authToken string, req request.CreateListenerRequest) (resource.CreateListenerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateListener", ctx, authToken, req)
	ret0, _ := ret[0].(resource.CreateListenerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateListener indicates an expected call of CreateListener.
func (mr *MockILoadbalancerServiceMockRecorder) CreateListener(ctx, authToken, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateListener", reflect.TypeOf((*MockILoadbalancerService)(nil).CreateListener), ctx, authToken, req)
}

// CreateLoadBalancer mocks base method.
func (m *MockILoadbalancerService) CreateLoadBalancer(ctx context.Context, authToken string, req request.CreateLoadBalancerRequest) (resource.CreateLoadBalancerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoadBalancer", ctx, authToken, req)
	ret0, _ := ret[0].(resource.CreateLoadBalancerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLoadBalancer indicates an expected call of CreateLoadBalancer.
func (mr *MockILoadbalancerServiceMockRecorder) CreateLoadBalancer(ctx, authToken, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoadBalancer", reflect.TypeOf((*MockILoadbalancerService)(nil).CreateLoadBalancer), ctx, authToken, req)
}

// CreateMember mocks base method.
func (m *MockILoadbalancerService) CreateMember(ctx context.Context, authToken, poolID string, req request.AddMemberRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMember", ctx, authToken, poolID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMember indicates an expected call of CreateMember.
func (mr *MockILoadbalancerServiceMockRecorder) CreateMember(ctx, authToken, poolID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMember", reflect.TypeOf((*MockILoadbalancerService)(nil).CreateMember), ctx, authToken, poolID, req)
}

// CreatePool mocks base method.
func (m *MockILoadbalancerService) CreatePool(ctx context.Context, authToken string, req request.CreatePoolRequest) (resource.CreatePoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePool", ctx, authToken, req)
	ret0, _ := ret[0].(resource.CreatePoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePool indicates an expected call of CreatePool.
func (mr *MockILoadbalancerServiceMockRecorder) CreatePool(ctx, authToken, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePool", reflect.TypeOf((*MockILoadbalancerService)(nil).CreatePool), ctx, authToken, req)
}

// DeleteLoadbalancer mocks base method.
func (m *MockILoadbalancerService) DeleteLoadbalancer(ctx context.Context, authToken, loadBalancerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadbalancer", ctx, authToken, loadBalancerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoadbalancer indicates an expected call of DeleteLoadbalancer.
func (mr *MockILoadbalancerServiceMockRecorder) DeleteLoadbalancer(ctx, authToken, loadBalancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadbalancer", reflect.TypeOf((*MockILoadbalancerService)(nil).DeleteLoadbalancer), ctx, authToken, loadBalancerID)
}

// DeleteLoadbalancerListeners mocks base method.
func (m *MockILoadbalancerService) DeleteLoadbalancerListeners(ctx context.Context, authToken, listenerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadbalancerListeners", ctx, authToken, listenerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoadbalancerListeners indicates an expected call of DeleteLoadbalancerListeners.
func (mr *MockILoadbalancerServiceMockRecorder) DeleteLoadbalancerListeners(ctx, authToken, listenerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadbalancerListeners", reflect.TypeOf((*MockILoadbalancerService)(nil).DeleteLoadbalancerListeners), ctx, authToken, listenerID)
}

// DeleteLoadbalancerPools mocks base method.
func (m *MockILoadbalancerService) DeleteLoadbalancerPools(ctx context.Context, authToken, poolID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadbalancerPools", ctx, authToken, poolID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoadbalancerPools indicates an expected call of DeleteLoadbalancerPools.
func (mr *MockILoadbalancerServiceMockRecorder) DeleteLoadbalancerPools(ctx, authToken, poolID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadbalancerPools", reflect.TypeOf((*MockILoadbalancerService)(nil).DeleteLoadbalancerPools), ctx, authToken, poolID)
}

// FindListenerIDByLoadBalancerAndPort mocks base method.
func (m *MockILoadbalancerService) FindListenerIDByLoadBalancerAndPort(ctx context.Context, authToken, lbID, protocol string, port int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindListenerIDByLoadBalancerAndPort", ctx, authToken, lbID, protocol, port)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindListenerIDByLoadBalancerAndPort indicates an expected call of FindListenerIDByLoadBalancerAndPort.
func (mr *MockILoadbalancerServiceMockRecorder) FindListenerIDByLoadBalancerAndPort(ctx, authToken, lbID, protocol, port any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindListenerIDByLoadBalancerAndPort", reflect.TypeOf((*MockILoadbalancerService)(nil).FindListenerIDByLoadBalancerAndPort), ctx, authToken, lbID, protocol, port)
}

// FindLoadBalancerIDByName mocks base method.
func (m *MockILoadbalancerService) FindLoadBalancerIDByName(ctx context.Context, authToken, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLoadBalancerIDByName", ctx, authToken, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLoadBalancerIDByName indicates an expected call of FindLoadBalancerIDByName.
func (mr *MockILoadbalancerServiceMockRecorder) FindLoadBalancerIDByName(ctx, authToken, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLoadBalancerIDByName", reflect.TypeOf((*MockILoadbalancerService)(nil).FindLoadBalancerIDByName), ctx, authToken, name)
}

// FindPoolIDForListener mocks base method.
func (m *MockILoadbalancerService) FindPoolIDForListener(ctx context.Context, authToken, listenerID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPoolIDForListener", ctx, authToken, listenerID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPoolIDForListener indicates an expected call of FindPoolIDForListener.
func (mr *MockILoadbalancerServiceMockRecorder) FindPoolIDForListener(ctx, authToken, listenerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPoolIDForListener", reflect.TypeOf((*MockILoadbalancerService)(nil).FindPoolIDForListener), ctx, authToken, listenerID)
}

// GetAmphoraesVrrpIp mocks base method.
func (m *MockILoadbalancerService) GetAmphoraesVrrpIp(authToken, loadBalancerID string) (resource.GetAmphoraesVrrpIpResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAmphoraesVrrpIp", authToken, loadBalancerID)
	ret0, _ := ret[0].(resource.GetAmphoraesVrrpIpResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAmphoraesVrrpIp indicates an expected call of GetAmphoraesVrrpIp.
func (mr *MockILoadbalancerServiceMockRecorder) GetAmphoraesVrrpIp(authToken, loadBalancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAmphoraesVrrpIp", reflect.TypeOf((*MockILoadbalancerService)(nil).GetAmphoraesVrrpIp), authToken, loadBalancerID)
}

// GetLoadBalancerListeners mocks base method.
func (m *MockILoadbalancerService) GetLoadBalancerListeners(ctx context.Context, authToken, loadBalancerID string) (resource.GetLoadBalancerListenersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadBalancerListeners", ctx, authToken, loadBalancerID)
	ret0, _ := ret[0].(resource.GetLoadBalancerListenersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoadBalancerListeners indicates an expected call of GetLoadBalancerListeners.
func (mr *MockILoadbalancerServiceMockRecorder) GetLoadBalancerListeners(ctx, authToken, loadBalancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadBalancerListeners", reflect.TypeOf((*MockILoadbalancerService)(nil).GetLoadBalancerListeners), ctx, authToken, loadBalancerID)
}

// GetLoadBalancerPools mocks base method.
func (m *MockILoadbalancerService) GetLoadBalancerPools(ctx context.Context, authToken, loadBalancerID string) (resource.GetLoadBalancerPoolsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadBalancerPools", ctx, authToken, loadBalancerID)
	ret0, _ := ret[0].(resource.GetLoadBalancerPoolsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoadBalancerPools indicates an expected call of GetLoadBalancerPools.
func (mr *MockILoadbalancerServiceMockRecorder) GetLoadBalancerPools(ctx, authToken, loadBalancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadBalancerPools", reflect.TypeOf((*MockILoadbalancerService)(nil).GetLoadBalancerPools), ctx, authToken, loadBalancerID)
}

// GetPoolDetail mocks base method.
func (m *MockILoadbalancerService) GetPoolDetail(ctx context.Context, authToken, poolID string) (resource.PoolDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPoolDetail", ctx, authToken, poolID)
	ret0, _ := ret[0].(resource.PoolDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPoolDetail indicates an expected call of GetPoolDetail.
func (mr *MockILoadbalancerServiceMockRecorder) GetPoolDetail(ctx, authToken, poolID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoolDetail", reflect.TypeOf((*MockILoadbalancerService)(nil).GetPoolDetail), ctx, authToken, poolID)
}

// ListListener mocks base method.
func (m *MockILoadbalancerService) ListListener(ctx context.Context, authToken, listenerID string) (resource.ListListenerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListListener", ctx, authToken, listenerID)
	ret0, _ := ret[0].(resource.ListListenerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListListener indicates an expected call of ListListener.
func (mr *MockILoadbalancerServiceMockRecorder) ListListener(ctx, authToken, listenerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListListener", reflect.TypeOf((*MockILoadbalancerService)(nil).ListListener), ctx, authToken, listenerID)
}

// ListLoadBalancer mocks base method.
func (m *MockILoadbalancerService) ListLoadBalancer(ctx context.Context, authToken, loadBalancerID string) (resource.ListLoadBalancerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLoadBalancer", ctx, authToken, loadBalancerID)
	ret0, _ := ret[0].(resource.ListLoadBalancerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLoadBalancer indicates an expected call of ListLoadBalancer.
func (mr *MockILoadbalancerServiceMockRecorder) ListLoadBalancer(ctx, authToken, loadBalancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLoadBalancer", reflect.TypeOf((*MockILoadbalancerService)(nil).ListLoadBalancer), ctx, authToken, loadBalancerID)
}

// ListLoadBalancerIDsByName mocks base method.
func (m *MockILoadbalancerService) ListLoadBalancerIDsByName(ctx context.Context, authToken, name string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLoadBalancerIDsByName", ctx, authToken, name)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLoadBalancerIDsByName indicates an expected call of ListLoadBalancerIDsByName.
func (mr *MockILoadbalancerServiceMockRecorder) ListLoadBalancerIDsByName(ctx, authToken, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLoadBalancerIDsByName", reflect.TypeOf((*MockILoadbalancerService)(nil).ListLoadBalancerIDsByName), ctx, authToken, name)
}

// LoadBalancerAbsent mocks base method.
func (m *MockILoadbalancerService) LoadBalancerAbsent(ctx context.Context, authToken, loadBalancerID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadBalancerAbsent", ctx, authToken, loadBalancerID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadBalancerAbsent indicates an expected call of LoadBalancerAbsent.
func (mr *MockILoadbalancerServiceMockRecorder) LoadBalancerAbsent(ctx, authToken, loadBalancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadBalancerAbsent", reflect.TypeOf((*MockILoadbalancerService)(nil).LoadBalancerAbsent), ctx, authToken, loadBalancerID)
}

// WaitForLoadBalancerDeleted mocks base method.
func (m *MockILoadbalancerService) WaitForLoadBalancerDeleted(ctx context.Context, authToken, loadBalancerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForLoadBalancerDeleted", ctx, authToken, loadBalancerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForLoadBalancerDeleted indicates an expected call of WaitForLoadBalancerDeleted.
func (mr *MockILoadbalancerServiceMockRecorder) WaitForLoadBalancerDeleted(ctx, authToken, loadBalancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForLoadBalancerDeleted", reflect.TypeOf((*MockILoadbalancerService)(nil).WaitForLoadBalancerDeleted), ctx, authToken, loadBalancerID)
}

// MockICloudflareService is a mock of ICloudflareService interface.
type MockICloudflareService struct {
	ctrl     *gomock.Controller
	recorder *MockICloudflareServiceMockRecorder
	isgomock struct{}
}

// MockICloudflareServiceMockRecorder is the mock recorder for MockICloudflareService.
type MockICloudflareServiceMockRecorder struct {
	mock *MockICloudflareService
}

// NewMockICloudflareService creates a new mock instance.
func NewMockICloudflareService(ctrl *gomock.Controller) *MockICloudflareService {
	mock := &MockICloudflareService{ctrl: ctrl}
	mock.recorder = &MockICloudflareServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICloudflareService) EXPECT() *MockICloudflareServiceMockRecorder {
	return m.recorder
}

// AddDNSRecordToCloudflare mocks base method.
func (m *MockICloudflareService) AddDNSRecordToCloudflare(ctx context.Context, loadBalancerIP, loadBalancerSubdomainHash, clusterName string) (resource.AddDNSRecordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDNSRecordToCloudflare", ctx, loadBalancerIP, loadBalancerSubdomainHash, clusterName)
	ret0, _ := ret[0].(resource.AddDNSRecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDNSRecordToCloudflare indicates an expected call of AddDNSRecordToCloudflare.
func (mr *MockICloudflareServiceMockRecorder) AddDNSRecordToCloudflare(ctx, loadBalancerIP, loadBalancerSubdomainHash, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDNSRecordToCloudflare", reflect.TypeOf((*MockICloudflareService)(nil).AddDNSRecordToCloudflare), ctx, loadBalancerIP, loadBalancerSubdomainHash, clusterName)
}

// DeleteDNSRecord mocks base method.
func (m *MockICloudflareService) DeleteDNSRecord(ctx context.Context, recordID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDNSRecord", ctx, recordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDNSRecord indicates an expected call of DeleteDNSRecord.
func (mr *MockICloudflareServiceMockRecorder) DeleteDNSRecord(ctx, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDNSRecord", reflect.TypeOf((*MockICloudflareService)(nil).DeleteDNSRecord), ctx, recordID)
}

// DeleteDNSRecordFromCloudflare mocks base method.
func (m *MockICloudflareService) DeleteDNSRecordFromCloudflare(ctx context.Context, dnsRecordID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDNSRecordFromCloudflare", ctx, dnsRecordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDNSRecordFromCloudflare indicates an expected call of DeleteDNSRecordFromCloudflare.
func (mr *MockICloudflareServiceMockRecorder) DeleteDNSRecordFromCloudflare(ctx, dnsRecordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDNSRecordFromCloudflare", reflect.TypeOf((*MockICloudflareService)(nil).DeleteDNSRecordFromCloudflare), ctx, dnsRecordID)
}

// UpdateDNSRecordContent mocks base method.
func (m *MockICloudflareService) UpdateDNSRecordContent(ctx context.Context, recordID, ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDNSRecordContent", ctx, recordID, ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDNSRecordContent indicates an expected call of UpdateDNSRecordContent.
func (mr *MockICloudflareServiceMockRecorder) UpdateDNSRecordContent(ctx, recordID, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDNSRecordContent", reflect.TypeOf((*MockICloudflareService)(nil).UpdateDNSRecordContent), ctx, recordID, ip)
}

// MockIIdentityService is a mock of IIdentityService interface.
type MockIIdentityService struct {
	ctrl     *gomock.Controller
	recorder *MockIIdentityServiceMockRecorder
	isgomock struct{}
}

// MockIIdentityServiceMockRecorder is the mock recorder for MockIIdentityService.
type MockIIdentityServiceMockRecorder struct {
	mock *MockIIdentityService
}

// NewMockIIdentityService creates a new mock instance.
func NewMockIIdentityService(ctrl *gomock.Controller) *MockIIdentityService {
	mock := &MockIIdentityService{ctrl: ctrl}
	mock.recorder = &MockIIdentityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIIdentityService) EXPECT() *MockIIdentityServiceMockRecorder {
	return m.recorder
}

// AuthenticateWithApplicationCredential mocks base method.
func (m *MockIIdentityService) AuthenticateWithApplicationCredential(ctx context.Context, applicationCredentialID, applicationCredentialSecret string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateWithApplicationCredential", ctx, applicationCredentialID, applicationCredentialSecret)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateWithApplicationCredential indicates an expected call of AuthenticateWithApplicationCredential.
func (mr *MockIIdentityServiceMockRecorder) AuthenticateWithApplicationCredential(ctx, applicationCredentialID, applicationCredentialSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateWithApplicationCredential", reflect.TypeOf((*MockIIdentityService)(nil).AuthenticateWithApplicationCredential), ctx, applicationCredentialID, applicationCredentialSecret)
}

// CheckAuthToken mocks base method.
func (m *MockIIdentityService) CheckAuthToken(ctx context.Context, authToken, projectID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAuthToken", ctx, authToken, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAuthToken indicates an expected call of CheckAuthToken.
func (mr *MockIIdentityServiceMockRecorder) CheckAuthToken(ctx, authToken, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAuthToken", reflect.TypeOf((*MockIIdentityService)(nil).CheckAuthToken), ctx, authToken, projectID)
}

// CreateApplicationCredential mocks base method.
func (m *MockIIdentityService) CreateApplicationCredential(ctx context.Context, clusterUUID, authToken string) (resource.CreateApplicationCredentialResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApplicationCredential", ctx, clusterUUID, authToken)
	ret0, _ := ret[0].(resource.CreateApplicationCredentialResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApplicationCredential indicates an expected call of CreateApplicationCredential.
func (mr *MockIIdentityServiceMockRecorder) CreateApplicationCredential(ctx, clusterUUID, authToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplicationCredential", reflect.TypeOf((*MockIIdentityService)(nil).CreateApplicationCredential), ctx, clusterUUID, authToken)
}

// DeleteApplicationCredential mocks base method.
func (m *MockIIdentityService) DeleteApplicationCredential(ctx context.Context, authToken, projectID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApplicationCredential", ctx, authToken, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApplicationCredential indicates an expected call of DeleteApplicationCredential.
func (mr *MockIIdentityServiceMockRecorder) DeleteApplicationCredential(ctx, authToken, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApplicationCredential", reflect.TypeOf((*MockIIdentityService)(nil).DeleteApplicationCredential), ctx, authToken, projectID)
}

// MockINodeGroupsService is a mock of INodeGroupsService interface.
type MockINodeGroupsService struct {
	ctrl     *gomock.Controller
	recorder *MockINodeGroupsServiceMockRecorder
	isgomock struct{}
}

// MockINodeGroupsServiceMockRecorder is the mock recorder for MockINodeGroupsService.
type MockINodeGroupsServiceMockRecorder struct {
	mock *MockINodeGroupsService
}

// NewMockINodeGroupsService creates a new mock instance.
func NewMockINodeGroupsService(ctrl *gomock.Controller) *MockINodeGroupsService {
	mock := &MockINodeGroupsService{ctrl: ctrl}
	mock.recorder = &MockINodeGroupsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINodeGroupsService) EXPECT() *MockINodeGroupsServiceMockRecorder {
	return m.recorder
}

// AddNode mocks base method.
func (m *MockINodeGroupsService) AddNode(ctx context.Context, authToken, clusterUUID, nodeGroupUUID string) (resource.AddNodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNode", ctx, authToken, clusterUUID, nodeGroupUUID)
	ret0, _ := ret[0].(resource.AddNodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNode indicates an expected call of AddNode.
func (mr *MockINodeGroupsServiceMockRecorder) AddNode(ctx, authToken, clusterUUID, nodeGroupUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNode", reflect.TypeOf((*MockINodeGroupsService)(nil).AddNode), ctx, authToken, clusterUUID, nodeGroupUUID)
}

// CreateNodeGroup mocks base method.
func (m *MockINodeGroupsService) CreateNodeGroup(ctx context.Context, authToken, clusterID string, req request.CreateNodeGroupRequest) (resource.CreateNodeGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodeGroup", ctx, authToken, clusterID, req)
	ret0, _ := ret[0].(resource.CreateNodeGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNodeGroup indicates an expected call of CreateNodeGroup.
func (mr *MockINodeGroupsServiceMockRecorder) CreateNodeGroup(ctx, authToken, clusterID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodeGroup", reflect.TypeOf((*MockINodeGroupsService)(nil).CreateNodeGroup), ctx, authToken, clusterID, req)
}

// DeleteNode mocks base method.
func (m *MockINodeGroupsService) DeleteNode(ctx context.Context, authToken, clusterID, nodeGroupID, id string) (resource.DeleteNodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNode", ctx, authToken, clusterID, nodeGroupID, id)
	ret0, _ := ret[0].(resource.DeleteNodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNode indicates an expected call of DeleteNode.
func (mr *MockINodeGroupsServiceMockRecorder) DeleteNode(ctx, authToken, clusterID, nodeGroupID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNode", reflect.TypeOf((*MockINodeGroupsService)(nil).DeleteNode), ctx, authToken, clusterID, nodeGroupID, id)
}

// DeleteNodeGroup mocks base method.
func (m *MockINodeGroupsService) DeleteNodeGroup(ctx context.Context, authToken, clusterID, nodeGroupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNodeGroup", ctx, authToken, clusterID, nodeGroupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNodeGroup indicates an expected call of DeleteNodeGroup.
func (mr *MockINodeGroupsServiceMockRecorder) DeleteNodeGroup(ctx, authToken, clusterID, nodeGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNodeGroup", reflect.TypeOf((*MockINodeGroupsService)(nil).DeleteNodeGroup), ctx, authToken, clusterID, nodeGroupID)
}

// GetNodeGroups mocks base method.
func (m *MockINodeGroupsService) GetNodeGroups(ctx context.Context, authToken, clusterID, nodeGroupID string) ([]resource.NodeGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeGroups", ctx, authToken, clusterID, nodeGroupID)
	ret0, _ := ret[0].([]resource.NodeGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeGroups indicates an expected call of GetNodeGroups.
func (mr *MockINodeGroupsServiceMockRecorder) GetNodeGroups(ctx, authToken, clusterID, nodeGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeGroups", reflect.TypeOf((*MockINodeGroupsService)(nil).GetNodeGroups), ctx, authToken, clusterID, nodeGroupID)
}

// GetNodeGroupsByClusterUUID mocks base method.
func (m *MockINodeGroupsService) GetNodeGroupsByClusterUUID(ctx context.Context, clusterUUID string) ([]resource.NodeGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeGroupsByClusterUUID", ctx, clusterUUID)
	ret0, _ := ret[0].([]resource.NodeGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeGroupsByClusterUUID indicates an expected call of GetNodeGroupsByClusterUUID.
func (mr *MockINodeGroupsServiceMockRecorder) GetNodeGroupsByClusterUUID(ctx, clusterUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeGroupsByClusterUUID", reflect.TypeOf((*MockINodeGroupsService)(nil).GetNodeGroupsByClusterUUID), ctx, clusterUUID)
}

// UpdateNodeGroups mocks base method.
func (m *MockINodeGroupsService) UpdateNodeGroups(ctx context.Context, authToken, clusterID, nodeGroupID string, req request.UpdateNodeGroupRequest) (resource.UpdateNodeGroupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNodeGroups", ctx, authToken, clusterID, nodeGroupID, req)
	ret0, _ := ret[0].(resource.UpdateNodeGroupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNodeGroups indicates an expected call of UpdateNodeGroups.
func (mr *MockINodeGroupsServiceMockRecorder) UpdateNodeGroups(ctx, authToken, clusterID, nodeGroupID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNodeGroups", reflect.TypeOf((*MockINodeGroupsService)(nil).UpdateNodeGroups), ctx, authToken, clusterID, nodeGroupID, req)
}
